import { describe, expect, it } from "vitest"

import { FITS } from "../src"
import { Card } from "../src/card"

function getHeaderKeywords(buffer: ArrayBuffer): string[] {
  const ascii = new TextDecoder("ascii")
  const keywords: string[] = []

  for (let offset = 0; offset < buffer.byteLength; offset += Card.LENGTH) {
    const record = ascii.decode(buffer.slice(offset, offset + Card.LENGTH))
    const keyword = Card.fromImage(record, false).keyword
    keywords.push(keyword)
    if (keyword === "END") {
      break
    }
  }

  while (keywords.at(-2) === "") {
    keywords.splice(-2, 1)
  }

  return keywords
}

describe("writer header helpers", () => {
  it("keeps mandatory cards first and preserves user card order", () => {
    const fits = FITS.fromDataArray([1, 2, 3, 4], 16, [2, 2])

    fits.header.append("OBJECT", "M42")
    fits.header.appendComment("Observation metadata")
    fits.header.insertAt(1, "OBSERVER", "Annie Jump Cannon")
    fits.header.appendBlank("Digitization")
    fits.header.appendHistory("Generated by tests")

    expect(getHeaderKeywords(fits.toBuffer())).toEqual([
      "SIMPLE",
      "BITPIX",
      "NAXIS",
      "NAXIS1",
      "NAXIS2",
      "OBJECT",
      "OBSERVER",
      "COMMENT",
      "",
      "HISTORY",
      "END",
    ])
  })

  it("round-trips repeated COMMENT/HISTORY cards and blank separators", () => {
    const fits = FITS.fromDataArray([1, 2], 16, [2])

    fits.header.appendComment("Scanned photographic plate")
    fits.header.appendComment("Second commentary line")
    fits.header.appendBlank("Axis metadata")
    fits.header.appendHistory("Generated by tests")
    fits.header.append("OBJECT", "HD 172167")
    fits.header.appendHistory("Validated by reader")

    const parsed = FITS.fromBuffer(fits.toBuffer(), null)

    expect(parsed.header.getComments("COMMENT")).toEqual([
      "Scanned photographic plate",
      "Second commentary line",
    ])
    expect(parsed.header.getComments("")).toEqual(["Axis metadata"])
    expect(parsed.header.getComments("HISTORY")).toEqual([
      "Generated by tests",
      "Validated by reader",
    ])
  })

  it("supports unified set and targeted removal", () => {
    const fits = FITS.fromDataArray([1], 16, [1])

    fits.header.append("OBJECT", "M42")
    fits.header.set("OBJECT", "M43", { comment: "Updated target" })
    fits.header.appendComment("Keep me")
    fits.header.appendComment("Remove me")

    expect(fits.header.remove("COMMENT", 0)).toBe(true)
    expect(fits.header.remove("COMMENT", 5)).toBe(false)

    fits.header.set("OBSERVER", "Cecilia Payne", { comment: "Catalog review" })
    fits.header.set("OBSERVER", undefined)

    expect(fits.header.getValue("OBJECT")).toBe("M43")
    expect(fits.header.getComment("OBJECT")).toBe("Updated target")
    expect(fits.header.getComments("COMMENT")).toEqual(["Remove me"])
    expect(fits.header.getValue("OBSERVER")).toBeUndefined()
  })

  it("adds axis metadata without inventing omitted values", () => {
    const fits = FITS.fromDataArray([1, 2, 3], -64, [3])

    fits.header.addAxis(1, {
      ctype: "WAVE",
      cunit: "Angstrom",
      crpix: 1,
      crval: 4000,
      cdelt: 0.8,
    })

    expect(fits.header.getValue("CTYPE1")).toBe("WAVE")
    expect(fits.header.getValue("CUNIT1")).toBe("Angstrom")
    expect(fits.header.getValue("CRPIX1")).toBe(1)
    expect(fits.header.getValue("CRVAL1")).toBe(4000)
    expect(fits.header.getValue("CDELT1")).toBe(0.8)
    expect(fits.header.getValue("CROTA1")).toBeUndefined()

    fits.header.addAxis(1, { crval: 4100 })
    expect(fits.header.getValue("CRVAL1")).toBe(4100)
  })
})

describe("typed array constructors", () => {
  it("round-trips floating and integer typed arrays", () => {
    const float64Fits = FITS.fromTypedArray(new Float64Array([1.25, -2.5, 3.75]), -64, [3])
    const float32Fits = FITS.fromTypedArray(new Float32Array([1.5, -2.25, 3.5]), -32, [3])
    const int32Fits = FITS.fromTypedArray(new Int32Array([1, -2, 3]), 32, [3])
    const uint16Fits = FITS.fromTypedArray(new Uint16Array([0, 1, 32767]), 16, [3])

    expect(Array.from(float64Fits.data.getData(), ({ value }) => value)).toEqual([1.25, -2.5, 3.75])
    expect(Array.from(float32Fits.data.getData(), ({ value }) => value)).toEqual([1.5, -2.25, 3.5])
    expect(Array.from(int32Fits.data.getData(), ({ value }) => value)).toEqual([1, -2, 3])
    expect(Array.from(uint16Fits.data.getData(), ({ value }) => value)).toEqual([0, 1, 32767])
  })

  it("validates typed array length against axes", () => {
    expect(() => FITS.fromTypedArray(new Float32Array([1, 2]), -32, [3])).toThrow(RangeError)
  })

  it("writes unsigned 16-bit images using BZERO and BSCALE", () => {
    const fits = FITS.fromUint16Array(new Uint16Array([0, 32768, 65535]), [3])

    expect(fits.header.getValue("BITPIX")).toBe(16)
    expect(fits.header.getValue("BSCALE")).toBe(1)
    expect(fits.header.getValue("BZERO")).toBe(32768)
    expect(Array.from(fits.data.getData(), ({ value }) => value)).toEqual([-32768, 0, 32767])

    const parsed = FITS.fromBuffer(fits.toBuffer(), null)
    expect(parsed.header.getValue("BSCALE")).toBe(1)
    expect(parsed.header.getValue("BZERO")).toBe(32768)
    expect(Array.from(parsed.data.getData(), ({ value }) => value)).toEqual([-32768, 0, 32767])
  })
})
